### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by Anu8050** [Anu8050/Hellomsg#6]
- [x] Display below message if button is clicked without mentioning the files
- [x] Please select atleast two files to perform merge operation. 
- [x] Please enter the file name to proceed.
- [x] After showing the above message, focus to the textbox. 
- [x] mention (Optional) for the third file 
- [x] show the path where the merged file is created. 
- [x] The merged file is located in the below path. 
- [x] Nex to merged file, put another button called "Preview merged file" 
- [x] Reset all the fields after merge 
- [x] add Reset button to clear all the fields and operation
